name: MysticPickaxe
version: '1.0-SNAPSHOT'
main: refil.mysticpickaxe.Refilmysticpickaxe
api-version: '1.21'
authors: [ Refil ]
description: Mystic Pickaxe that mines 3x3xx
commands:
  mysticpickaxe:
    description: MysticPickaxe command with subcommands.
    usage: /mysticpickaxe <subcommand>

